### ISSUE TITLE
Train on customed dataset，get 'tuple' object has no attribute 'log_softmax' error

### ISSUE THREAD

**Issue by nessie7purple** [XinyuLyu/FGPL#8]
## ❓ Questions and Help
My command is：

--config-file
"/data/disk2/dy/FGPL-master/configs/e2e_relation_X_101_32_8_FPN_1x_transformer_FPGL.yaml"
MODEL.ROI_RELATION_HEAD.USE_GT_BOX
True
MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL
False
MODEL.ROI_RELATION_HEAD.PREDICTOR
TransformerPredictor
MODEL.ROI_RELATION_HEAD.PREDICT_USE_BIAS
True
DTYPE
"float32"
SOLVER.IMS_PER_BATCH
16
TEST.IMS_PER_BATCH
1
SOLVER.MAX_ITER
2400
SOLVER.BASE_LR
1e-3
SOLVER.SCHEDULE.TYPE
WarmupMultiStepLR
SOLVER.STEPS
"(1000, 1600)"
SOLVER.VAL_PERIOD
600
SOLVER.CHECKPOINT_PERIOD
600
GLOVE_DIR
./datasets/vg/
MODEL.PRETRAINED_DETECTOR_CKPT
/data/disk2/dy/FGPL-master/checkpoints/pretrained_faster_rcnn/model_final.pth
MODEL.ROI_RELATION_HEAD.USE_EXTRA_LOSS
False
MODEL.ROI_RELATION_HEAD.USE_LOGITS_REWEIGHT
False
MODEL.ROI_RELATION_HEAD.MITIGATION_FACTOR_HYPER
1.5
MODEL.ROI_RELATION_HEAD.COMPENSATION_FACTOR_HYPRT
2.0
MODEL.ROI_RELATION_HEAD.USE_CONTRA_LOSS
False
MODEL.ROI_RELATION_HEAD.USE_CONTRA_BCE
False
MODEL.ROI_RELATION_HEAD.CONTRA_DISTANCE_LOSS_VALUE
0.6
MODEL.ROI_RELATION_HEAD.CONTRA_DISTANCE_LOSS_COF
0.1
MODEL.ROI_RELATION_HEAD.CANDIDATE_NUMBER
5
OUTPUT_DIR
/data/disk2/dy/FGPL-master/checkpoints/trans_sgcls
MODEL.ROI_RELATION_HEAD.TRANSFORMER.DROPOUT_RATE
0.3

**Comment by nessie7purple** [comment]
I was trying to try on my customed dataset but got dimension mismatch. After getting hints from issue#4, I tried again to train a model without using FGPL, and then there's error about maskrcnn_benchmark/modeling/roi_heads/relation_head/loss.py "rel_dists" is not referenced, so I did a little modification as below.
![image](https://github.com/XinyuLyu/FGPL/assets/96714497/ea54d909-b063-449d-992b-dd9137c853b9)
And then there goes the error:
/data/disk2/dy/FGPL-master/maskrcnn_benchmark/structures/boxlist_ops.py:46: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370117127/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  keep = (
Traceback (most recent call last):
  File "/data/disk2/dy/FGPL-master/tools/relation_train_net.py", line 417, in <module>
    main()
  File "/data/disk2/dy/FGPL-master/tools/relation_train_net.py", line 408, in main
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "/data/disk2/dy/FGPL-master/tools/relation_train_net.py", line 168, in train
    loss_dict, relation_loss = model(images=images, targets=targets, iteration=iteration)
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/apex-0.1-py3.8-linux-x86_64.egg/apex/amp/_initialize.py", line 196, in new_fwd
    output = old_fwd(*applier(args, input_caster),
  File "/data/disk2/dy/FGPL-master/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 55, in forward
    x, result, detector_losses, relation_loss = self.roi_heads(features, proposals, targets, logger, iteration)
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/disk2/dy/FGPL-master/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 72, in forward
    x, detections, loss_relation, loss_relation_tuple = self.relation(features, detections, targets, logger,iteration)
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/disk2/dy/FGPL-master/maskrcnn_benchmark/modeling/roi_heads/relation_head/relation_head.py", line 93, in forward
    loss_relation, loss_refine = self.loss_evaluator(proposals, rel_labels, relation_logits, refine_logits,
  File "/data/disk2/dy/FGPL-master/maskrcnn_benchmark/modeling/roi_heads/relation_head/loss.py", line 302, in __call__
    loss_relation_total = self.criterion_loss(relation_logits, rel_labels.long())  # [1214,42], [1214,1]
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 961, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/data/disk2/apps/envs/scene_graph_benchmark/lib/python3.8/site-packages/torch/nn/functional.py", line 1605, in log_softmax
    ret = input.log_softmax(dim)
AttributeError: 'tuple' object has no attribute 'log_softmax'


I've searched network for solutions and actually get some. But it doesn't work with the code. Could you please check and give some advice?
Thank you in advance!

**Comment by nessie7purple** [comment]
@XinyuLyu
